on:
  release:
    types: [published]

concurrency:
  group: "build"
  cancel-in-progress: true

env:
  MODRINTH_ID: "1UPdBpGk"
  CURSEFORGE_ID: "XXXXXX"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.2'

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Download Packwiz
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: go.yml
          repo: packwiz/packwiz
          name: Linux 64-bit x86

      - name: Build Packs
        run: |
          chmod +x packwiz
          bash .github/workflows/build.sh ${{ github.event.release.tag_name }}

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: "The Theatre v${{ github.event.release.tag_name }}"
          loaders: fabric
          game-versions: 1.20.1
          java: 17
          files: build/the-theatre.mrpack

          modrinth-id: "${{ env.MODRINTH_ID }}"
          #curseforge-id: "${{ env.CURSEFORGE_ID }}"

          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          version: "${{ github.event.release.tag_name }}"
          version-type: release

      - name: Publish (Lite)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: "The Theatre (Lite) v${{ github.event.release.tag_name }}"
          loaders: fabric
          game-versions: 1.20.1
          java: 17
          files: build/the-theatre-lite.mrpack

          modrinth-id: "${{ env.MODRINTH_ID }}"
          #curseforge-id: "${{ env.CURSEFORGE_ID }}"

          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          version: "${{ github.event.release.tag_name }}"
          version-type: release
